version: '3.4'

services:
    gateway:
        build: gateway/
        container_name: gateway
        environment:
            - CONFIG_LOC=/run/secret/config.json
        volumes:
            - ./config.json:/run/secret/config.json
    backend:
        build: 
            context: backend/
            target: dev
        container_name: backend
        environment:
            - CONFIG_LOC=/run/secret/config.json
            - PORT=2468
            - GIN_MODE=test
        ports:
            - 2468:2468
        volumes:
            - ./config.json:/run/secret/config.json
