version: '3.4'

services:
    gateway:
        build: 
            context: gateway/
            target: dev
        container_name: dc-gateway
        environment:
            - CONFIG_LOC=/run/secrets/config
        volumes:
            - ./config.json:/run/secrets/config
    backend:
        build: 
            context: backend/
            target: dev
        container_name: dc-backend
        environment:
            - CONFIG_LOC=/run/secrets/config
        ports:
            - 2468:2468
        volumes:
            - ./config.json:/run/secrets/config
