version: '3.4'

services:
    gateway:
        build: gateway/
        container_name: gateway
        environment:
            - CONFIG_LOC=/run/secret/config.json
        secrets:
            - config
    backend:
        build: 
            context: backend/
            target: dev
        container_name: backend
        environment:
            - CONFIG_LOC=/run/secret/config.json
        ports:
            - 2468:2468
        secrets:
            - config

secrets:
    config:
        file: ./config.json
