# This docker compose file is a dev docker compose that only launches only 
# the backend service alone
#
# To run go test instead of running the app, uncomment the command: line 
#
# When moving to production, simply change the build target to "prod" instead

version: "3.4"

services:
    backend:
        container_name: backend
        build: 
            context: .
            target: dev
        environment:
         - CONFIG_LOC=./config.json
         - PORT=2468
         - GIN_MODE=test
        ports:
            - 2468:2468
        volumes:
         - ../config.json:/app/config.json
        #command: go test
